<a href="https://colab.research.google.com/github/profshai/classification/blob/main/model_evaluation_performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Models Evaluation and Performance

Breast Cancer Detection
The datasent is the UCL Breast Cancer Wisconsin (Original) Data Set (1992). The sample size is 699 with 10 attributes.

Attribute Information:

- Sample code number: id number
- Clump Thickness: 1 - 10
- Uniformity of Cell Size: 1 - 10
- Uniformity of Cell Shape: 1 - 10
- Marginal Adhesion: 1 - 10
- Single Epithelial Cell Size: 1 - 10
- Bare Nuclei: 1 - 10
- Bland Chromatin: 1 - 10
- Normal Nucleoli: 1 - 10
- Mitoses: 1 - 10
- Class: (2 for benign, 4 for malignant)

_Objective_: We want evaluate the performance of the classification models on this dataset.

### Import libraries

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Import data

In [4]:
data = pd.read_csv('Data.csv')
data

Sample code number  Clump Thickness  ...  Mitoses  Class
0               1000025                5  ...        1      2
1               1002945                5  ...        1      2
2               1015425                3  ...        1      2
3               1016277                6  ...        1      2
4               1017023                4  ...        1      2
..                  ...              ...  ...      ...    ...
678              776715                3  ...        1      2
679              841769                2  ...        1      2
680              888820                5  ...        2      4
681              897471                4  ...        1      4
682              897471                4  ...        1      4

[683 rows x 11 columns]

In [6]:
X = data.iloc[:, 1:-1].values
y = data.iloc[:, -1].values

### Split data into Training and test data

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Training Classification models on training set

## Logistic Regression

In [8]:
from sklearn.linear_model import LogisticRegression
lr_classifier = LogisticRegression(random_state = 0)
lr_classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [9]:
y_pred_lr = lr_classifier.predict(X_test)

### K-Nearest Neighbors

In [10]:
from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors=5, metric = 'minkowski', p = 2)
knn_classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [11]:
y_pred_knn = knn_classifier.predict(X_test)

### Support Vector Machines

In [12]:
from sklearn.svm import SVC
svm_classifier = SVC(kernel = 'linear', random_state = 0)
svm_classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [13]:
y_pred_svm = svm_classifier.predict(X_test)

### Kernel SVM

In [14]:
from sklearn.svm import SVC
ksvm_classifier = SVC(kernel = 'rbf', random_state = 0)
ksvm_classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [15]:
y_pred_ksvm = ksvm_classifier.predict(X_test)

### Naive Bayes

In [16]:
from sklearn.naive_bayes import GaussianNB
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [18]:
y_pred_nb = nb_classifier.predict(X_test)

### Decision Tree Classification

In [19]:
from sklearn.tree import DecisionTreeClassifier
dt_classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
dt_classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [20]:
y_pred_dt = dt_classifier.predict(X_test)

### Random Forest Classification

In [21]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [23]:
y_pred_rf = rf_classifier.predict(X_test)

## Model performance

### Logistic Regression 

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_lr)
print(cm)
lr_accuracy = accuracy_score(y_test, y_pred_lr)

[[103   4]
 [  5  59]]


### K-Nearest Neighbors

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_knn)
print(cm)
knn_accuracy = accuracy_score(y_test, y_pred_knn)

[[103   4]
 [  4  60]]


### Support Vector Machines

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_svm)
print(cm)
svm_accuracy = accuracy_score(y_test, y_pred_svm)

[[102   5]
 [  5  59]]


### Kernel SVM

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_ksvm)
print(cm)
ksvm_accuracy = accuracy_score(y_test, y_pred_ksvm)

[[102   5]
 [  3  61]]


### Naive Bayes

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_nb)
print(cm)
nb_accuracy = accuracy_score(y_test, y_pred_nb)

[[99  8]
 [ 2 62]]


### Decision Tree classification

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_dt)
print(cm)
dt_accuracy = accuracy_score(y_test, y_pred_dt)

[[104   3]
 [  4  60]]


### Random Forest Classification

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_rf)
print(cm)
rf_accuracy = accuracy_score(y_test, y_pred_rf)

[[104   3]
 [  5  59]]


In [31]:
print('Logistic Regression Accuracy: {:.2f} %'.format(lr_accuracy))
print('K-NN Accuracy: {:.2f} %'.format(knn_accuracy))
print('SVM Accuracy: {:.2f} %'.format(svm_accuracy))
print('Kernel SVM Accuracy: {:.2f} %'.format(ksvm_accuracy))
print('Naive Bayes Accuracy: {:.2f} %'.format(nb_accuracy))
print('Decision Tree Accuracy: {:.2f} %'.format(dt_accuracy))
print('Random Forest Accuracy: {:.2f} %'.format(rf_accuracy))

Logistic Regression Accuracy: 0.95 %
K-NN Accuracy: 0.95 %
SVM Accuracy: 0.94 %
Kernel SVM Accuracy: 0.95 %
Naive Bayes Accuracy: 0.94 %
Decision Tree Accuracy: 0.96 %
Random Forest Accuracy: 0.95 %


Conclusion: The Decision Tree has the best accuracy score.